# Prometheus Configuration v2.45.0
# Enterprise-grade monitoring configuration for Task Management System
# Implements comprehensive metrics collection, security monitoring, and performance tracking

global:
  # Global settings for all scrape targets
  scrape_interval: 15s     # Default scrape interval for metrics collection
  evaluation_interval: 1m  # Interval for evaluating rules
  scrape_timeout: 10s     # Timeout for scrape requests
  
  # External labels for identifying the Prometheus instance
  external_labels:
    environment: production
    region: primary
    cluster: task-management-prod

# Rule files for alerts and recording rules
rule_files:
  - "rules/alert-rules.yaml"      # Alert rules for infrastructure, application, and security monitoring
  - "rules/recording-rules.yaml"  # Recording rules for SLOs and pre-computed metrics

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']
      scheme: https
      timeout: 10s
      api_version: v2
      # TLS configuration for secure communication
      tls_config:
        cert_file: /etc/prometheus/certs/prometheus.crt
        key_file: /etc/prometheus/certs/prometheus.key
        ca_file: /etc/prometheus/certs/ca.crt

# Scrape configurations for various metrics endpoints
scrape_configs:
  # Prometheus self-monitoring
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  # API Services monitoring with enhanced security and filtering
  - job_name: api-services
    metrics_path: /metrics
    scheme: https
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['task-management']
    # TLS configuration for secure metrics collection
    tls_config:
      cert_file: /etc/prometheus/certs/prometheus.crt
      key_file: /etc/prometheus/certs/prometheus.key
      ca_file: /etc/prometheus/certs/ca.crt
    # Relabel configs to filter relevant pods
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: 'api-.*'
        action: keep
    # Metric relabel configs to focus on performance metrics
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'http_request_duration_seconds.*'
        action: keep

  # Node Exporter for infrastructure metrics
  - job_name: node-exporter
    kubernetes_sd_configs:
      - role: node
    scheme: https
    tls_config:
      insecure_skip_verify: false
      cert_file: /etc/prometheus/certs/prometheus.crt
      key_file: /etc/prometheus/certs/prometheus.key
      ca_file: /etc/prometheus/certs/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token

  # Kubernetes state metrics
  - job_name: kube-state-metrics
    static_configs:
      - targets: ['kube-state-metrics:8080']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'kube_pod_container_status.*|kube_deployment_status.*'
        action: keep

# Remote write configuration for long-term storage with Thanos
remote_write:
  - url: 'http://thanos-receive:19291/api/v1/receive'
    remote_timeout: 30s
    queue_config:
      capacity: 10000
      max_shards: 200
      min_shards: 1
      max_samples_per_send: 500
    # Relabel configs to optimize storage
    write_relabel_configs:
      - source_labels: [__name__]
        regex: '.*_total|.*_sum|.*_count'
        action: keep

# Storage configuration for local TSDB
storage:
  tsdb:
    retention_time: 15d           # Local storage retention period
    min_block_duration: 2h        # Minimum block duration
    max_block_duration: 24h       # Maximum block duration
    no_lockfile: false           # Enable lockfile for safety
    allow_overlapping_blocks: false  # Prevent overlapping blocks
    wal_compression: true        # Enable WAL compression