apiVersion: v1
kind: Secret
metadata:
  name: task-management-secrets
  namespace: default
  labels:
    app: task-management
    environment: base
    component: secrets
    managed-by: kubernetes
  annotations:
    azure.key-vault/enabled: "true"
    azure.key-vault/secret-rotation: "enabled"
    azure.key-vault/rotation-poll-interval: "1h"
    azure.key-vault/secret-store: "azure"
    azure.key-vault/vault-name: "task-mgmt-kv"
    azure.key-vault/tenant-id: "${AZURE_TENANT_ID}"
    security.vault.azure/secret-version: "latest"
    security.vault.azure/auto-rotation: "true"
    security.vault.azure/rotation-frequency: "30d"
    compliance.security/gdpr: "compliant"
    compliance.security/soc2: "compliant"
    compliance.security/iso27001: "compliant"
type: Opaque
data:
  # Database Credentials
  DATABASE_URL: ${AZURE_KV_DATABASE_URL}
  DATABASE_USER: ${AZURE_KV_DATABASE_USER}
  DATABASE_PASSWORD: ${AZURE_KV_DATABASE_PASSWORD}
  
  # JWT Authentication
  JWT_SECRET: ${AZURE_KV_JWT_SECRET}
  JWT_REFRESH_SECRET: ${AZURE_KV_JWT_REFRESH_SECRET}
  
  # Azure AD B2C OAuth Configuration
  AZURE_AD_TENANT_ID: ${AZURE_KV_AD_TENANT_ID}
  AZURE_AD_CLIENT_ID: ${AZURE_KV_AD_CLIENT_ID}
  AZURE_AD_CLIENT_SECRET: ${AZURE_KV_AD_CLIENT_SECRET}
  
  # Redis Cache Credentials
  REDIS_PASSWORD: ${AZURE_KV_REDIS_PASSWORD}
  
  # Encryption Keys
  ENCRYPTION_KEY: ${AZURE_KV_ENCRYPTION_KEY}
  MFA_SECRET_KEY: ${AZURE_KV_MFA_SECRET}
  
  # Session Management
  SESSION_SECRET: ${AZURE_KV_SESSION_SECRET}
  COOKIE_SECRET: ${AZURE_KV_COOKIE_SECRET}
  
  # Storage & Services
  STORAGE_ACCOUNT_KEY: ${AZURE_KV_STORAGE_KEY}
  SMTP_PASSWORD: ${AZURE_KV_SMTP_PASSWORD}

---
# RBAC Policy for Secret Access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["task-management-secrets"]
  verbs: ["get"]

---
# Role Binding for Service Accounts
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-reader-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: task-management-sa
  namespace: default
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io