# Service Accounts for Task Management System Components
# Version: v1
# Purpose: Defines service accounts with enhanced security controls and compliance features
# for various microservices and system components

---
# API Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-service-account
  namespace: taskmanagement
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/part-of: task-management-system
    app.kubernetes.io/managed-by: kustomize
    security.taskmanagement.io/audit-level: high
    compliance.taskmanagement.io/data-classification: internal
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    kubernetes.io/service-account.name: api-service-account
    security.taskmanagement.io/token-expiration: "24h"
    security.taskmanagement.io/requires-audit: "true"
    security.taskmanagement.io/auto-rotation: "enabled"
    compliance.taskmanagement.io/last-review: "2024-01-01T00:00:00Z"
    monitoring.taskmanagement.io/alert-on-use: "true"
automountServiceAccountToken: false
imagePullSecrets:
  - name: registry-credentials

---
# Analytics Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service-account
  namespace: taskmanagement
  labels:
    app.kubernetes.io/name: analytics
    app.kubernetes.io/part-of: task-management-system
    app.kubernetes.io/managed-by: kustomize
    security.taskmanagement.io/audit-level: high
    compliance.taskmanagement.io/data-classification: internal
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    kubernetes.io/service-account.name: analytics-service-account
    security.taskmanagement.io/token-expiration: "24h"
    security.taskmanagement.io/requires-audit: "true"
    security.taskmanagement.io/auto-rotation: "enabled"
    compliance.taskmanagement.io/last-review: "2024-01-01T00:00:00Z"
    monitoring.taskmanagement.io/alert-on-use: "true"
automountServiceAccountToken: false
imagePullSecrets:
  - name: registry-credentials

---
# Monitoring Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring-service-account
  namespace: taskmanagement
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: task-management-system
    app.kubernetes.io/managed-by: kustomize
    security.taskmanagement.io/audit-level: high
    compliance.taskmanagement.io/data-classification: internal
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    kubernetes.io/service-account.name: monitoring-service-account
    security.taskmanagement.io/token-expiration: "24h"
    security.taskmanagement.io/requires-audit: "true"
    security.taskmanagement.io/auto-rotation: "enabled"
    compliance.taskmanagement.io/last-review: "2024-01-01T00:00:00Z"
    monitoring.taskmanagement.io/alert-on-use: "true"
automountServiceAccountToken: false
imagePullSecrets:
  - name: registry-credentials

---
# Notification Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-account
  namespace: taskmanagement
  labels:
    app.kubernetes.io/name: notification
    app.kubernetes.io/part-of: task-management-system
    app.kubernetes.io/managed-by: kustomize
    security.taskmanagement.io/audit-level: high
    compliance.taskmanagement.io/data-classification: internal
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    kubernetes.io/service-account.name: notification-service-account
    security.taskmanagement.io/token-expiration: "24h"
    security.taskmanagement.io/requires-audit: "true"
    security.taskmanagement.io/auto-rotation: "enabled"
    compliance.taskmanagement.io/last-review: "2024-01-01T00:00:00Z"
    monitoring.taskmanagement.io/alert-on-use: "true"
automountServiceAccountToken: false
imagePullSecrets:
  - name: registry-credentials