# Loki Configuration v2.9.0
# Enterprise-grade log aggregation and analysis system

# Global server configuration
server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  grpc_server_max_recv_msg_size: 67108864  # 64MB
  log_level: info
  http_server_idle_timeout: 120s
  grpc_server_max_concurrent_streams: 1000

# Authentication and security configuration
auth_enabled: true

# Distributor configuration for high availability
distributor:
  ring:
    kvstore:
      store: memberlist
    heartbeat_timeout: 1m
  ha_tracker:
    enable_ha_tracker: true
    max_prompt_count: 3
    fail_over_timeout: 30s

# Ingester configuration with 3x replication
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3
      heartbeat_period: 5s
      heartbeat_timeout: 1m
  chunk_idle_period: 1h
  max_chunk_age: 2h
  chunk_target_size: 1048576  # 1MB
  chunk_retain_period: 30s
  max_transfer_retries: 0
  wal:
    enabled: true
    dir: /loki/wal
    replay_memory_ceiling: 512MB

# Schema configuration for log storage
schema_config:
  configs:
    - from: "2023-01-01"
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# Storage configuration
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks
  hedging:
    at: 250ms
    max_per_second: 20
    up_to: 3

# Query and ingestion limits configuration
limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # 7 days
  max_entries_limit_per_query: 5000
  max_query_length: 721h  # 30 days
  max_query_parallelism: 32
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  per_tenant_rate_limit: true
  per_stream_rate_limit: 3MB
  per_stream_rate_limit_burst: 15MB
  max_global_streams_per_user: 5000
  max_query_series: 10000

# Chunk store configuration
chunk_store_config:
  max_look_back_period: 720h  # 30 days
  chunk_cache_config:
    enable_fifocache: true
    fifocache:
      max_size_bytes: 1073741824  # 1GB
      validity: 24h

# Table manager for retention
table_manager:
  retention_deletes_enabled: true
  retention_period: 720h  # 30 days
  poll_interval: 12h
  creation_grace_period: 24h

# Compactor configuration
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

# Ruler configuration for alerting
ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: memberlist
  enable_api: true
  enable_alertmanager_v2: true
  evaluation_interval: 1m
  poll_interval: 1m
  concurrent_executions: 10

# Query frontend configuration
query_frontend:
  align_queries_with_step: true
  cache_results: true
  max_retries: 5
  split_queries_by_interval: 30m
  query_sharding_enabled: true
  query_sharding_total_shards: 16

# Query scheduler configuration
query_scheduler:
  max_outstanding_requests_per_tenant: 100
  scheduler_address: query-scheduler:9095

# Memberlist configuration for cluster communication
memberlist:
  join_members:
    - loki-memberlist
  abort_if_cluster_join_fails: false
  max_join_retries: 10
  max_join_backoff: 1m
  min_join_backoff: 1s
  bind_port: 7946
  bind_addr: 0.0.0.0
  gossip_interval: 200ms
  gossip_nodes: 3
  retransmit_factor: 3

# Runtime configuration
runtime_config:
  file: /etc/loki/runtime.yaml
  period: 10s

# Analytics
analytics:
  reporting_enabled: false